/** @format */

export const TEXT_INPUT_COMPONENT = 'TEXT_INPUT_COMPONENT';
export const TEXT_SELECT_COMPONENT = 'TEXT_SELECT_COMPONENT';
export const TEXT_SELECT_CHECKBOX_MULTI_COMPONENT = 'TEXT_SELECT_CHECKBOX_MULTI_COMPONENT';
export const TEXT_AREA_INPUT_COMPONENT = 'TEXT_AREA_INPUT_COMPONENT';
export const CUSTOM_INPUT_COMPONENT = 'CUSTOM_INPUT_COMPONENT';
